apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: atm-app
  name: atm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atm-app
  template:
    metadata:
      labels:
        app: atm-app
    spec:
      containers:
      - name: atm
        image: 786770494633.dkr.ecr.ap-south-1.amazonaws.com/atm-app:latest
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: atm-app
  name: svc
spec:
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  type: NodePort
