apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: atm-app
  name: atm-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: atm-app
  template:
    metadata:
      labels:
        app: atm-app
    spec:
      containers:
      - name: atm
        image: 786770494633.dkr.ecr.ap-south-1.amazonaws.com/atm-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: atm-app
    k8s-app: atm-app
  name: atm-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: atm-app
